### ISSUE TITLE
STIG/CIS Hardening for RKE2

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-rke2-image-builder#10]
DISA has released a STIG guide for RKE2:
- https://public.cyber.mil/announcement/disa-releases-the-rancher-government-solutions-rke2-security-technical-implementation-guide/
- https://ranchergovernment.com/blog/disa-validates-rancher-government-solutions-kubernetes-distribution

There is also a CIS Hardening guide produced by Rancher:
- https://docs.rke2.io/security/hardening_guide

Either as part of the AMI defaults (default config file?) or IaC to deploy RKE2 we should provide these configs out of the box.

**Comment by austenbryan** [comment]
@mjnagel glad to see this is captured in the backlog. @unicornbunny182 asked me about it today in our sync.  Have you chatted with anyone at HNCD that may have had to follow this pattern as well? How do we validated the STIG in CI. Apologies if my questions are uneducated. We can find time in Gather too

**Comment by mjnagel** [comment]
Have not checked with them yet - threw a feeler out there and will see what comes of that. Hopefully some goodness we can borrow from there. For what its worth I believe most of the STIG and CIS hardening is default on RKE2, so it _should_ be easy-ish.

In terms of validating the STIG in CI - not sure I have an answer right now. I believe the STIG offers commands/checks to validate each, couldn't quickly find any automation around the RKE2 stig, but https://www.open-scap.org/tools/ could help? I know you can use some of their tooling to validate [XCCDF](https://csrc.nist.gov/projects/security-content-automation-protocol/specifications/xccdf), which is published for the RKE2 STIG. Either way I think we can absolutely check the STIG and produce an artifact with the check results, just might be more or less work on us depending on whether oscap will help here.

**Comment by mjnagel** [comment]
Closing based on https://github.com/defenseunicorns/uds-rke2-image-builder/pull/5
