### ISSUE TITLE
Image Builder Pipeline

### ISSUE THREAD

**Issue by justin-o12** [defenseunicorns/uds-rke2-image-builder#45]
We need a pipeline that will provide some automation and consistency to the image build process.  It could be kicked off with a cron or manual action.  It would be nice to then store the ID in AWS Parameter Store (for AWS images, of course).  Then, we could always get the latest my querying the param `uds-rke2-rhel-latest` or `uds-rke2-ubuntu-latest`.  This would run jobs in all environments--dev, staging, and prod.

We could run the pipeline from this repo or the repo for the destination environment.

**Comment by joelmccoy** [comment]
We have a cron publishing new AMIs monthly [here](https://github.com/defenseunicorns/uds-rke2-image-builder/blob/main/.github/workflows/publish-aws.yaml#L14).  Rest of this work will be completed by https://github.com/defenseunicorns/uds-infrastructure/issues/367
