### ISSUE TITLE
Build out image/workflow for a RHEL based AMI

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-rke2-image-builder#7]
Following the example done with Ubuntu as part of https://github.com/defenseunicorns/uds-rke2-image-builder/issues/1 , build out an AMI based on RHEL that meets the below requirements.

Requirements:
- RHEL Base image
- STIG'd image
- RKE2 pre-installed

**Comment by mjnagel** [comment]
I think we can close this out, concur @jacobbmay ?

**Comment by jacobbmay** [comment]
Yes. Forgot to close it after the PR merged.
